package com.typingfrontier.mental

object PortugueseSentenceRepository {

    val frases = listOf(

        "O gato preto dorme no sofá",
        "Maria comprou pão na padaria",
        "O detetive analisou as pistas",
        "A professora explicou a matéria",
        "O jogador venceu a partida",
        "A criança abriu o presente",
        "O cientista descobriu uma nova estrela",
        "O aluno resolveu o problema",
        "O carro vermelho passou rápido",
        "O escritor terminou o livro",

        "O médico examinou o paciente",
        "O vento forte derrubou a árvore",
        "A menina desenhou uma casa",
        "O professor corrigiu a prova",
        "O cachorro latiu durante a noite",
        "O motorista parou no sinal",
        "O artista pintou um quadro",
        "O programador criou um aplicativo",
        "A equipe venceu o campeonato",
        "O fazendeiro colheu o milho",

        "O policial investigou o caso",
        "O garoto encontrou uma moeda",
        "A cozinheira preparou o jantar",
        "O pássaro construiu um ninho",
        "O engenheiro projetou a ponte",
        "O piloto pousou o avião",
        "O aluno fez a tarefa",
        "O escritor publicou um artigo",
        "A cidade recebeu turistas",
        "O cientista estudou o vírus",

        "O jogador chutou a bola",
        "O médico salvou o paciente",
        "O professor ensinou matemática",
        "O cachorro perseguiu o gato",
        "A menina leu um livro",
        "O atleta correu a maratona",
        "O mecânico consertou o carro",
        "O jornalista escreveu a notícia",
        "O detetive resolveu o mistério",
        "O garoto aprendeu a nadar",

        "O agricultor plantou sementes",
        "O piloto acelerou o carro",
        "A criança brincou no parque",
        "O professor explicou a lição",
        "O cientista analisou os dados",
        "O músico tocou violão",
        "O jogador marcou um gol",
        "A menina ganhou um presente",
        "O médico receitou o remédio",
        "O policial prendeu o ladrão",

        "O estudante estudou para a prova",
        "O escritor revisou o texto",
        "O pintor misturou as cores",
        "O garoto chutou a bola",
        "A professora leu a história",
        "O atleta levantou o peso",
        "O cientista fez um experimento",
        "O detetive encontrou pistas",
        "O aluno respondeu a pergunta",
        "O médico atendeu o paciente",

        "O policial protegeu a cidade",
        "O professor iniciou a aula",
        "O engenheiro calculou a estrutura",
        "O escritor imaginou personagens",
        "O músico compôs uma melodia",
        "O estudante fez anotações",
        "O piloto verificou os motores",
        "O programador escreveu código",
        "O cientista publicou pesquisa",
        "O atleta treinou intensamente",

        "O garoto abriu a porta",
        "O professor explicou o conceito",
        "O detetive interrogou o suspeito",
        "O jogador comemorou a vitória",
        "A menina escreveu uma carta",
        "O cientista estudou o planeta",
        "O mecânico trocou o pneu",
        "O agricultor regou a plantação",
        "O médico analisou exames",
        "O aluno fez uma pergunta",

        "O professor avaliou o trabalho",
        "O atleta ganhou a corrida",
        "O escritor publicou um conto",
        "O cientista fez uma descoberta",
        "O detetive seguiu a pista",
        "O músico afinou o instrumento",
        "O garoto encontrou um mapa",
        "O piloto iniciou a viagem",
        "O médico observou os sintomas",
        "O aluno terminou o exercício"

    )
}