package com.typingfrontier.mental

data class OrthographyChallenge(
    val correct: String,
    val wrong: String,
    val tip: String
)

object PortugueseOrthographyRepository {
    val desafios = listOf(
        // --- S e SS ---
        OrthographyChallenge("ASSADO", "ASADO", "Assado (comida) usa SS."),
        OrthographyChallenge("PÊSSEGO", "PÊSEGO", "Pêssego é com SS."),
        OrthographyChallenge("MASSA", "MASA", "Massa (macarrão/construção) é com SS."),
        OrthographyChallenge("PASSEIO", "PASEIO", "Passeio usa SS."),
        OrthographyChallenge("SOSSEGO", "SOSEGO", "Sossego é com SS."),
        OrthographyChallenge("PROGRESSO", "PROGRESO", "Progresso usa SS."),
        OrthographyChallenge("SUCESSO", "SUCESO", "Sucesso se escreve com SS."),
        OrthographyChallenge("MISSÃO", "MISÃO", "Missão é com SS."),
        OrthographyChallenge("VASSOURA", "VASOURA", "Vassoura usa SS."),
        OrthographyChallenge("DEZESSEIS", "DEZESEIS", "Dezesseis é com SS."),
        OrthographyChallenge("PASSARELA", "PASARELA", "Passarela usa SS."),
        OrthographyChallenge("BÚSSOLA", "BÚSOLA", "Bússola é com SS."),
        OrthographyChallenge("GESSO", "GESO", "Gesso usa SS."),
        OrthographyChallenge("PRESSA", "PRESA", "Pressa (rapidez) é com SS."),
        OrthographyChallenge("PESSOA", "PESOA", "Pessoa usa SS."),
        OrthographyChallenge("DISSE", "DISE", "Disse (verbo dizer) é com SS."),
        OrthographyChallenge("PASSAGEM", "PASAGEM", "Passagem usa SS."),
        OrthographyChallenge("PÁSSARO", "PÁSARO", "Pássaro é com SS."),
        OrthographyChallenge("NECESSÁRIO", "NECESÁRIO", "Necessário usa SS."),
        OrthographyChallenge("EXPRESSÃO", "EXPRESÃO", "Expressão é com SS."),
        OrthographyChallenge("PROFISSÃO", "PROFISÃO", "Profissão usa SS."),
        OrthographyChallenge("COMISSÃO", "COMISÃO", "Comissão é com SS."),
        OrthographyChallenge("DISCUSSÃO", "DISCUSÃO", "Discussão usa SS."),
        OrthographyChallenge("ACESSO", "ACESO", "Acesso (entrada) é com SS."),
        OrthographyChallenge("DEMISSÃO", "DEMISÃO", "Demissão usa SS."),
        OrthographyChallenge("PROCESSO", "PROCESO", "Processo é com SS."),
        OrthographyChallenge("POSSESSIVO", "POSESIVO", "Possessivo usa SS."),
        OrthographyChallenge("IMPRESSÃO", "IMPRESÃO", "Impressão é com SS."),
        OrthographyChallenge("DEPESSA", "DEPESA", "Depressa usa SS."),
        OrthographyChallenge("AVESSO", "AVESO", "Avesso é com SS."),

        // --- S e Z ---
        OrthographyChallenge("ANALISAR", "ANALIZAR", "Vem de 'análise' (com S)."),
        OrthographyChallenge("AVISAR", "AVIZAR", "Vem de 'aviso' (com S)."),
        OrthographyChallenge("PESQUISA", "PEZQUISA", "Pesquisa é com S."),
        OrthographyChallenge("ATRASO", "ATRAZO", "Atraso usa S."),
        OrthographyChallenge("EMPRESA", "EMPREZA", "Empresa é com S."),
        OrthographyChallenge("MESA", "MEZA", "Mesa usa S."),
        OrthographyChallenge("LISO", "LIZO", "Liso é com S."),
        OrthographyChallenge("BRASA", "BRAZA", "Brasa usa S."),
        OrthographyChallenge("CRISE", "CRIZE", "Crise é com S."),
        OrthographyChallenge("DESENHO", "DEZENHO", "Desenho usa S."),
        OrthographyChallenge("BATIZAR", "BATISAR", "Batizar é com Z."),
        OrthographyChallenge("CIVILIZAR", "CIVILISAR", "Civilizar usa Z."),
        OrthographyChallenge("DESLIZE", "DESLISE", "Deslize é com Z."),
        OrthographyChallenge("VAZIO", "VASIO", "Vazio usa Z."),
        OrthographyChallenge("COZINHA", "COSINHA", "Cozinha é com Z."),
        OrthographyChallenge("VIZINHO", "VISINHO", "Vizinho usa Z."),
        OrthographyChallenge("PRAZER", "PRASER", "Prazer é com Z."),
        OrthographyChallenge("TALVEZ", "TALVES", "Talvez usa Z no final."),
        OrthographyChallenge("ARROZ", "ARROS", "Arroz termina com Z."),
        OrthographyChallenge("CICATRIZ", "CICATRIS", "Cicatriz termina com Z."),
        OrthographyChallenge("NARIZ", "NARIS", "Nariz termina com Z."),
        OrthographyChallenge("VERNIZ", "VERNIS", "Verniz termina com Z."),
        OrthographyChallenge("RAPIDEZ", "RAPIDES", "Rapidez termina com Z."),
        OrthographyChallenge("ESTUPIDEZ", "ESTUPIDES", "Estupidez termina com Z."),
        OrthographyChallenge("ESCASSEZ", "ESCASSES", "Escassez termina com Z."),
        OrthographyChallenge("COZIDO", "COSIDO", "Cozido (alimento) é com Z."),
        OrthographyChallenge("AZUL", "ASUL", "Azul é com Z."),
        OrthographyChallenge("AMIZADE", "AMISADE", "Amizade usa Z."),
        OrthographyChallenge("BATIZADO", "BATISADO", "Batizado é com Z."),
        OrthographyChallenge("BUREAUCRACIA", "BUROCRACIA", "Burocracia usa S (derivado de bureau)."),

        // --- S e Ç ---
        OrthographyChallenge("EXCEÇÃO", "EXCESÃO", "Exceção é com Ç."),
        OrthographyChallenge("DANÇA", "DANSA", "Dança usa Ç."),
        OrthographyChallenge("CANÇÃO", "CANSÃO", "Canção é com Ç."),
        OrthographyChallenge("ESFORÇO", "ESFORSO", "Esforço usa Ç."),
        OrthographyChallenge("AÇÚCAR", "ASÚCAR", "Açúcar é com Ç."),
        OrthographyChallenge("CALÇA", "CALSA", "Calça usa Ç."),
        OrthographyChallenge("ESPERANÇA", "ESPERANSA", "Esperança é com Ç."),
        OrthographyChallenge("ALIANÇA", "ALIANSA", "Aliança usa Ç."),
        OrthographyChallenge("ENDEREÇO", "ENDERESO", "Endereço é com Ç."),
        OrthographyChallenge("BALANÇO", "BALANSO", "Balanço usa Ç."),
        OrthographyChallenge("ATENÇÃO", "ATENSAO", "Atenção é com Ç."),
        OrthographyChallenge("INTENÇÃO", "INTENSÃO", "Intenção usa Ç."),
        OrthographyChallenge("PRETENSÃO", "PRETENÇÃO", "Pretensão usa S."),
        OrthographyChallenge("COMPREENSÃO", "COMPREENÇÃO", "Compreensão usa S."),
        OrthographyChallenge("EXTENSÃO", "EXTENÇÃO", "Extensão usa S."),
        OrthographyChallenge("SUSPENSÃO", "SUSPENÇÃO", "Suspensão usa S."),
        OrthographyChallenge("INVENÇÃO", "INVENSÃO", "Invenção usa Ç."),
        OrthographyChallenge("DISTINÇÃO", "DISTINSÃO", "Distinção usa Ç."),
        OrthographyChallenge("REDAÇÃO", "REDASÃO", "Redação usa Ç."),
        OrthographyChallenge("CORAÇÃO", "CORASÃO", "Coração usa Ç."),
        OrthographyChallenge("PALHAÇO", "PALHASO", "Palhaço usa Ç."),
        OrthographyChallenge("CABEÇA", "CABESA", "Cabeça usa Ç."),
        OrthographyChallenge("JUSTIÇA", "JUSTISA", "Justiça usa Ç."),
        OrthographyChallenge("PREGUIÇA", "PREGUISA", "Preguiça usa Ç."),
        OrthographyChallenge("MOÇA", "MOSA", "Moça usa Ç."),
        OrthographyChallenge("AÇOUGUE", "ASOUGUE", "Açougue usa Ç."),
        OrthographyChallenge("ALMOÇO", "ALMOSO", "Almoço usa Ç."),
        OrthographyChallenge("DIFERENÇA", "DIFERENSA", "Diferença usa Ç."),
        OrthographyChallenge("LANCINANTE", "LANSINANTE", "Lancinante usa C."),
        OrthographyChallenge("PREGUIÇOSO", "PREGUISOSO", "Preguiçoso usa Ç."),

        // --- U e L ---
        OrthographyChallenge("DEGRAU", "DEGRAL", "Singular: degrau (com U)."),
        OrthographyChallenge("JORNAL", "JORNAU", "Singular: jornal (com L)."),
        OrthographyChallenge("PAPEL", "PAPEU", "Papel termina com L."),
        OrthographyChallenge("AZUL", "AZUU", "Azul termina com L."),
        OrthographyChallenge("HOTEL", "HOTEU", "Hotel termina com L."),
        OrthographyChallenge("FUNIL", "FUNIU", "Funil termina com L."),
        OrthographyChallenge("CHAPÉU", "CHAPÉL", "Chapéu termina com U."),
        OrthographyChallenge("TROFÉU", "TROFÉL", "Troféu termina com U."),
        OrthographyChallenge("CÉU", "CÉL", "Céu termina com U."),
        OrthographyChallenge("ANIMAL", "ANIMAU", "Animal termina com L."),
        OrthographyChallenge("CARNAVAL", "CARNAVAU", "Carnaval termina com L."),
        OrthographyChallenge("ANEL", "ANEU", "Anel termina com L."),
        OrthographyChallenge("QUARTEL", "QUARTEU", "Quartel termina com L."),
        OrthographyChallenge("CORONEL", "CORONEU", "Coronel termina com L."),
        OrthographyChallenge("MEL", "MEU", "Mel termina com L."),
        OrthographyChallenge("SAL", "SAU", "Sal termina com L."),
        OrthographyChallenge("SOL", "SOU", "Sol termina com L."),
        OrthographyChallenge("BRASIL", "BRASIU", "Brasil termina com L."),
        OrthographyChallenge("CANTIL", "CANTIU", "Cantil termina com L."),
        OrthographyChallenge("BARRIL", "BARRIU", "Barril termina com L."),
        OrthographyChallenge("BACALHAU", "BACALHAL", "Bacalhau termina com U."),
        OrthographyChallenge("MINGAU", "MINGAL", "Mingau termina com U."),
        OrthographyChallenge("DEGRAUS", "DEGRALS", "Plural de degrau é degraus."),
        OrthographyChallenge("TROFÉUS", "TROFÉS", "Plural de troféu é troféus."),
        OrthographyChallenge("PINCÉIS", "PINCÉIS", "Plural de pincel."),
        OrthographyChallenge("PAU", "PAL", "Pau (madeira) termina com U."),
        OrthographyChallenge("MAL", "MAU", "Mal (advérbio) oposto de bem."),
        OrthographyChallenge("MAU", "MAL", "Mau (adjetivo) oposto de bom."),
        OrthographyChallenge("LEGAL", "LEGAU", "Legal termina com L."),
        OrthographyChallenge("VARAL", "VARAU", "Varal termina com L."),

        // --- H e sem H ---
        OrthographyChallenge("HOMEM", "OMEM", "Homem tem H inicial."),
        OrthographyChallenge("HOJE", "OJE", "Hoje tem H inicial."),
        OrthographyChallenge("HORA", "ORA", "Hora (tempo) tem H."),
        OrthographyChallenge("HAVER", "AVER", "Verbo haver tem H."),
        OrthographyChallenge("HERANÇA", "ERANÇA", "Herança tem H."),
        OrthographyChallenge("HÁBITO", "ÁBITO", "Hábito tem H."),
        OrthographyChallenge("HERÓI", "ERÓI", "Herói tem H."),
        OrthographyChallenge("HORTA", "ORTA", "Horta tem H."),
        OrthographyChallenge("HONESTO", "ONESTO", "Honesto tem H."),
        OrthographyChallenge("HONRA", "ONRA", "Honra tem H."),
        OrthographyChallenge("HOTEL", "OTEL", "Hotel tem H."),
        OrthographyChallenge("HORIZONTE", "ORIZONTE", "Horizonte tem H."),
        OrthographyChallenge("HÁLITO", "ÁLITO", "Hálito tem H."),
        OrthographyChallenge("ÚMIDO", "HÚMIDO", "Úmido NÃO tem H."),
        OrthographyChallenge("OMBRO", "HOMBRO", "Ombro NÃO tem H."),
        OrthographyChallenge("ONTEM", "HONTEM", "Ontem NÃO tem H."),
        OrthographyChallenge("ERVA", "HERVA", "Erva NÃO tem H."),
        OrthographyChallenge("INVERNO", "HINVERNO", "Inverno NÃO tem H."),
        OrthographyChallenge("OVO", "HOVO", "Ovo NÃO tem H."),
        OrthographyChallenge("IDADE", "HIDADE", "Idade NÃO tem H."),
        OrthographyChallenge("HERESIA", "ERESIA", "Heresia tem H."),
        OrthographyChallenge("HIGIENE", "IGIENE", "Higiene tem H."),
        OrthographyChallenge("HÉLICE", "ÉLICE", "Hélice tem H."),
        OrthographyChallenge("HINO", "INO", "Hino tem H."),
        OrthographyChallenge("HABILIDADE", "ABILIDADE", "Habilidade tem H."),
        OrthographyChallenge("HARMONIA", "ARMONIA", "Harmonia tem H."),
        OrthographyChallenge("HOSPITAL", "OSPITAL", "Hospital tem H."),
        OrthographyChallenge("HUMILDADE", "UMILDADE", "Humildade tem H."),
        OrthographyChallenge("HERANÇA", "ERANÇA", "Herança tem H."),
        OrthographyChallenge("HEDIONDO", "EDIONDO", "Hediondo tem H.")
    )
}
